---
:ems:
  :ems_generic:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:

        :power:
          :critical:
            - GENERIC_instance_power_on
            - GENERIC_instance_power_off

:http_proxy:
  :generic:
    :host:
    :password:
    :port:
    :user:

:workers:
  :worker_base:
    :event_catcher:
      :event_catcher_generic:
        :poll: 20.seconds
    :queue_worker_base:
      :ems_metrics_collector_worker:
        :ems_metrics_collector_worker_generic: {}
      :ems_refresh_worker:
        :ems_refresh_worker_generic: {}

